---

- hosts: all
  become: true
  tasks:

  
  - name: update repository index
    apt:
      update_cache: yes


  - name: install apache2 package
    apt:
      name: apache2	
      state: latest

  - name: install php support lib
    apt:
      name: libapache2-mod-php
      state: latest

