---

- hosts: all
  become: true
  tasks: 
  - name: install apache2, php, python  packages
    package:
      name:
        - " {{ python_package }} "
        - " {{ apache_package }} "
        - " {{ php_package }} "
        - " {{ tomcat_package }} "
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


